image:
    - Visual Studio 2022  
    - Visual Studio 2019  

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\cc.asn1.commsdsl
shallow_clone: true             

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    COMMS_BRANCH: v5.2.2
    COMMSDSL_BRANCH: develop
    matrix:
        - CPP_STD: 11
        - CPP_STD: 14
        - CPP_STD: 17
        - CPP_STD: 20

matrix:
    fast_finish: false
    exclude:
        - image: Visual Studio 2017
          CPP_STD: 20                           
        
install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - if exist %BUILD_DIR% rmdir /S /Q %BUILD_DIR%
    - set COMMS_TAG=%COMMS_BRANCH%
    - set COMMSDSL_TAG=%COMMSDSL_BRANCH%
    - set COMMON_INSTALL_DIR=%BUILD_DIR%\install
    - set COMMON_BUILD_TYPE=%CONFIGURATION%
    - set COMMON_CXX_STANDARD=%CPP_STD%
    - set GENERATOR="%CMAKE_GENERATOR%"
    - set PLATFORM="%CMAKE_PLATFORM%"    
    - call script\prepare_externals.bat

build_script:
    - echo ------------------------- Building Project -------------------------
    - cd %BUILD_DIR%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%CMAKE_GENERATOR%" %PLATFORM_PARAM% ^
        -DCMAKE_INSTALL_PREFIX="%COMMON_INSTALL_DIR%" -DCMAKE_PREFIX_PATH="%COMMON_INSTALL_DIR%" -DCMAKE_CXX_STANDARD=%CPP_STD% ^
        -DCC_ASN1_BUILD_APPS=ON -DCC_ASN1_BUILD_UNIT_TESTS=ON
    - cmake --build . --config %CONFIGURATION% --target install



